# Generated by Django 5.1.3 on 2024-11-24 06:40

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "actif",
                    models.BooleanField(
                        choices=[(True, "Actif"), (False, "Inactif")], default=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(max_length=15, verbose_name="Téléphone"),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "ville",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Pays"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Code Postal"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=100)),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrateur"),
                            ("VENDEUR", "Vendeur"),
                            ("OVRIER", "Ouvrier"),
                            ("JOURNALIER", "Journalier"),
                        ],
                        default="VENDEUR",
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("date_embauche", models.DateField()),
                (
                    "actif",
                    models.BooleanField(
                        choices=[(True, "Actif"), (False, "Inactif")], default=False
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("contenu", models.TextField()),
                ("date_rapport", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("CDI", "Contrat à durée indéterminée"),
                            ("CDD", "Contrat à durée déterminée"),
                            ("Freelance", "Freelance"),
                            ("Stage", "Stage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("salaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="application.employe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "actif",
                    models.BooleanField(
                        choices=[(True, "Actif"), (False, "Inactif")], default=False
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="application.categorie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix Unitaire"
                    ),
                ),
                (
                    "quantite_commande",
                    models.PositiveIntegerField(verbose_name="Quantité Commandée"),
                ),
                (
                    "moyen_transport",
                    models.CharField(max_length=100, verbose_name="Moyen de Transport"),
                ),
                (
                    "prix_transport",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix du Transport",
                    ),
                ),
                ("date_livraison", models.DateField(verbose_name="Date de Livraison")),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "total_global",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Global",
                    ),
                ),
                (
                    "difference_jours",
                    models.IntegerField(default=0, verbose_name="Différence en jours"),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommandeApprovisionnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_commande",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Date de Commande"
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_cours", "En Cours"), ("livree", "Livrée")],
                        default="en_cours",
                        max_length=50,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="application.fournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="application.produit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emplacement",
                    models.CharField(
                        choices=[
                            ("entrepot_1", "Entrepôt 1"),
                            ("entrepot_2", "Entrepôt 2"),
                            ("magasin", "Magasin"),
                            ("reserve", "Réserve"),
                            ("autre", "Autre"),
                        ],
                        default="entrepot_1",
                        max_length=50,
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_stock", "En stock"),
                            ("rupture", "Rupture"),
                            ("en_approvisionnement", "En approvisionnement"),
                            ("reserve", "Réservé"),
                        ],
                        default="en_stock",
                        max_length=20,
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="application.produit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Administrateur"), ("VENDEUR", "Vendeur")],
                        default="VENDEUR",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Les groupes auxquels cet utilisateur appartient.",
                        related_name="utilisateur_groups",
                        to="auth.group",
                        verbose_name="groupes",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Les permissions spécifiques pour cet utilisateur.",
                        related_name="utilisateur_permissions",
                        to="auth.permission",
                        verbose_name="permissions utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
