# Generated by Django 5.1.3 on 2024-11-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0002_invoice_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="customer",
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_vente",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Vente"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventes",
                        to="application.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente",
                "verbose_name_plural": "Ventes",
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Quantité")),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Prix Unitaire"
                    ),
                ),
                (
                    "sous_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sous-Total",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_ventes",
                        to="application.produit",
                        verbose_name="Produit",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="application.vente",
                        verbose_name="Vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de Vente",
                "verbose_name_plural": "Lignes de Ventes",
            },
        ),
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
    ]
