# Generated by Django 5.1.3 on 2024-11-24 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_remove_invoice_customer_vente_lignevente_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vente",
            options={},
        ),
        migrations.RemoveField(
            model_name="vente",
            name="date_vente",
        ),
        migrations.RemoveField(
            model_name="vente",
            name="total",
        ),
        migrations.AddField(
            model_name="vente",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vente",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.client"
            ),
        ),
        migrations.CreateModel(
            name="VenteProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.produit",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventes_produits",
                        to="application.vente",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LigneVente",
        ),
    ]
