# Generated by Django 5.1.3 on 2024-11-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_alter_vente_options_remove_vente_date_vente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="total_global",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vente",
            name="total_vente",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
