# Generated by Django 5.1.3 on 2024-11-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_vente_total_global_vente_total_vente"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteproduit",
            name="sous_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
