# Generated by Django 5.1.3 on 2024-11-24 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0006_venteproduit_sous_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vente",
            name="total_global",
        ),
        migrations.RemoveField(
            model_name="vente",
            name="total_vente",
        ),
        migrations.RemoveField(
            model_name="venteproduit",
            name="sous_total",
        ),
    ]
