# Generated by Django 5.1.3 on 2024-11-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0007_remove_vente_total_global_remove_vente_total_vente_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vente",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventes",
                to="application.client",
            ),
        ),
    ]
