# Generated by Django 5.1.3 on 2024-11-26 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0008_alter_vente_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandeapprovisionnement",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes",
                to="application.stock",
            ),
        ),
    ]
