# Generated by Django 5.1.3 on 2024-11-26 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0009_alter_commandeapprovisionnement_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livraison",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="application.commandeapprovisionnement",
            ),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livraisons",
                to="application.commandeapprovisionnement",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="actif",
            field=models.BooleanField(
                choices=[(True, "Disponible"), (False, "Indisponible")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="produit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="application.produit",
            ),
        ),
    ]
