# Generated by Django 5.1.3 on 2024-11-26 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0011_alter_livraison_fournisseur_alter_livraison_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livraison",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.stock"
            ),
        ),
    ]
