# Generated by Django 5.1.3 on 2024-11-26 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0013_alter_livraison_fournisseur_alter_livraison_produit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livraison",
            name="fournisseur",
        ),
        migrations.AlterField(
            model_name="livraison",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livraisons_produit",
                to="application.commandeapprovisionnement",
            ),
        ),
    ]
