# Generated by Django 5.1.3 on 2024-11-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0014_remove_livraison_fournisseur_alter_livraison_produit"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Utilisateur associé à cet employé (facultatif).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employe",
                to="application.utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/utilisateurs/default.png",
                null=True,
                upload_to="images/utilisateurs/",
            ),
        ),
    ]
