# Generated by Django 5.1.3 on 2024-11-27 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0015_employe_user_utilisateur_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employe",
            name="user",
        ),
    ]
