# Generated by Django 5.1.3 on 2024-11-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0016_remove_employe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="employe",
            field=models.OneToOneField(
                blank=True,
                help_text="Employé associé à cet utilisateur.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateur",
                to="application.employe",
            ),
        ),
    ]
