# Generated by Django 5.1.3 on 2024-11-28 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0017_utilisateur_employe"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Utilisateur",
        ),
    ]
