# Generated by Django 5.1.3 on 2024-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0018_delete_utilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/images/produits/"
            ),
        ),
    ]
