# Generated by Django 5.1.3 on 2024-11-29 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0020_alter_produit_image_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="phone",
            new_name="telephone",
        ),
    ]
