# Generated by Django 5.1.3 on 2024-11-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0021_rename_phone_profile_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="First_name",
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="Last_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
