# Generated by Django 5.1.3 on 2024-11-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0023_remove_profile_first_name_remove_profile_last_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tache",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
