# Generated by Django 5.1.3 on 2024-11-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0024_profile_tache"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="tache",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
