# Generated by Django 5.1.3 on 2024-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0025_alter_profile_tache"),
    ]

    operations = [
        migrations.AddField(
            model_name="vente",
            name="statut_paiement",
            field=models.CharField(
                choices=[("payee", "Payée"), ("non_payee", "Non Payée")],
                default="non_payee",
                max_length=10,
                verbose_name="Statut Paiement",
            ),
        ),
    ]
